name: var_project
description: Var Project
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  camera: ^0.10.5+5
  google_mlkit_text_recognition: ^0.10.0
  permission_handler: ^11.0.1
  image_picker: ^1.0.4
  clipboard: ^0.1.3
  path_provider: ^2.1.1
  image_cropper: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
